name: Check Links

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  links:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: lycheeverse/lychee-action@v2
        with:
          args: README.md
          fail: true
